smtp_username = 'example@gmail.com'
smtp_password = 'example'
smtp_relay = 'smtp.gmail.com'
smtp_from = 'Example <example@gmail.com>'
password_reset_link = 'http://localhost:3000/reset-password'
jwt_secret = 'abc123'
allowed_origin = 'http://localhost:3000/'
